# Generated by Django 3.2.20 on 2023-09-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concerts', '0002_alter_concert_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concert',
            name='slug',
        ),
    ]
